-- Mobile Service Management System - Database Schema (Postgres / Supabase)
-- Notes:
-- - Uses BIGINT identity PKs for most tables
-- - Uses TEXT/VARCHAR fields for flexibility
-- - Ensures bookings.pincode references service_areas.pincode (serviceable pincode rule)
-- - Includes indexes for common lookup fields
-- - If deploying to Supabase, run in SQL editor. Adjust schema name if needed.

-- =========================
-- 1) users
-- =========================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  role text not null, -- e.g. 'admin', 'customer', 'technician'
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_role on public.users (role);
create index if not exists ix_users_created_at on public.users (created_at);

-- =========================
-- 2) service_areas
-- =========================
create table if not exists public.service_areas (
  id bigint generated by default as identity primary key,
  pincode varchar(6) not null unique,
  city text null,
  district text null,
  state text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_areas_pincode_format_chk check (pincode ~ '^[0-9]{6}$')
);

create index if not exists ix_service_areas_is_active on public.service_areas (is_active);
create index if not exists ix_service_areas_city on public.service_areas (city);

-- =========================
-- 3) customers
-- =========================
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id bigint unique null,
  full_name text not null,
  phone varchar(20) null,
  email text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fk_customers_user_id
    foreign key (user_id) references public.users (id) on delete set null
);

create index if not exists ix_customers_phone on public.customers (phone);
create index if not exists ix_customers_email on public.customers (email);

-- =========================
-- 4) technicians
-- =========================
create table if not exists public.technicians (
  id bigint generated by default as identity primary key,
  user_id bigint unique null,
  full_name text not null,
  phone varchar(20) null,
  skill_level text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fk_technicians_user_id
    foreign key (user_id) references public.users (id) on delete set null
);

create index if not exists ix_technicians_is_active on public.technicians (is_active);
create index if not exists ix_technicians_phone on public.technicians (phone);

-- =========================
-- 5) services
-- =========================
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text null,
  base_price numeric(12,2) null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_services_is_active on public.services (is_active);
create index if not exists ix_services_name on public.services (name);

-- =========================
-- 6) bookings
-- =========================
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_id bigint not null,
  service_id bigint not null,
  -- Pincode rule:
  -- bookings.pincode MUST match an existing service_areas.pincode.
  pincode varchar(6) not null,
  scheduled_at timestamptz null,
  address_line1 text null,
  address_line2 text null,
  notes text null,
  status text not null default 'Pending', -- Pending/In Progress/Completed/Cancelled
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_bookings_customer_id
    foreign key (customer_id) references public.customers (id) on delete restrict,
  constraint fk_bookings_service_id
    foreign key (service_id) references public.services (id) on delete restrict,
  constraint fk_bookings_pincode
    foreign key (pincode) references public.service_areas (pincode) on delete restrict,
  constraint bookings_pincode_format_chk check (pincode ~ '^[0-9]{6}$')
);

create index if not exists ix_bookings_customer_id on public.bookings (customer_id);
create index if not exists ix_bookings_service_id on public.bookings (service_id);
create index if not exists ix_bookings_pincode on public.bookings (pincode);
create index if not exists ix_bookings_status on public.bookings (status);
create index if not exists ix_bookings_created_at on public.bookings (created_at);

-- =========================
-- 7) repair_jobs
-- =========================
create table if not exists public.repair_jobs (
  id bigint generated by default as identity primary key,
  booking_id bigint not null,
  technician_id bigint null,
  issue_description text null,
  diagnosis text null,
  resolution text null,
  status text not null default 'Open', -- Open/In Progress/Resolved/Closed
  started_at timestamptz null,
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_repair_jobs_booking_id
    foreign key (booking_id) references public.bookings (id) on delete cascade,
  constraint fk_repair_jobs_technician_id
    foreign key (technician_id) references public.technicians (id) on delete set null
);

create index if not exists ix_repair_jobs_booking_id on public.repair_jobs (booking_id);
create index if not exists ix_repair_jobs_technician_id on public.repair_jobs (technician_id);
create index if not exists ix_repair_jobs_status on public.repair_jobs (status);

-- =========================
-- 8) invoices
-- =========================
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  booking_id bigint not null,
  invoice_number text unique not null,
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  status text not null default 'Draft', -- Draft/Sent/Paid/Void
  issued_at timestamptz null,
  due_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_invoices_booking_id
    foreign key (booking_id) references public.bookings (id) on delete cascade
);

create index if not exists ix_invoices_booking_id on public.invoices (booking_id);
create index if not exists ix_invoices_status on public.invoices (status);
create index if not exists ix_invoices_issued_at on public.invoices (issued_at);

-- =========================
-- 9) payments
-- =========================
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null,
  amount numeric(12,2) not null,
  method text not null, -- Cash/UPI/Card/etc
  status text not null default 'Captured', -- Pending/Captured/Failed/Refunded
  paid_at timestamptz null,
  reference text null,
  created_at timestamptz not null default now(),

  constraint fk_payments_invoice_id
    foreign key (invoice_id) references public.invoices (id) on delete cascade
);

create index if not exists ix_payments_invoice_id on public.payments (invoice_id);
create index if not exists ix_payments_status on public.payments (status);
create index if not exists ix_payments_paid_at on public.payments (paid_at);

-- =========================
-- 10) notifications
-- =========================
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint null,
  booking_id bigint null,
  channel text not null default 'sms', -- sms/email/push
  title text null,
  message text not null,
  status text not null default 'queued', -- queued/sent/failed
  sent_at timestamptz null,
  created_at timestamptz not null default now(),

  constraint fk_notifications_user_id
    foreign key (user_id) references public.users (id) on delete set null,
  constraint fk_notifications_booking_id
    foreign key (booking_id) references public.bookings (id) on delete cascade
);

create index if not exists ix_notifications_user_id on public.notifications (user_id);
create index if not exists ix_notifications_booking_id on public.notifications (booking_id);
create index if not exists ix_notifications_status on public.notifications (status);
